---
# updating params is mandatory. the check on params_regexp_replace_pairs is skipped 
# to provide users a failure message if the value is not set

- name: "Update the params file entries"
  include_tasks: update-params-file.yml
  with_items:
  - "{{ openshift_cluster_content }}"
  when:
  - item.content is defined
  - item.content != ""

# updating galaxy is optional, so we check here that galaxy_regexp_replace_pairs is set

- name: "Update galaxy requirements file"
  include_tasks: update-galaxy-requirements.yml
  with_items:
  - "{{ openshift_cluster_content }}"
  when: 
  - item.galaxy_requirements is defined
  - item.galaxy_requirements != ""
  - galaxy_regexp_replace_pairs is defined
  - galaxy_regexp_replace_pairs != ""

- name: "Update 'namespace: ' entries with a custom filter"
  set_fact:
    openshift_cluster_content: "{{ openshift_cluster_content | update_namespace(project_name_postfix) }}"
