---

- name: "Set default values"
  set_fact:
    target_namespace: ''
    file: "{{ item.file | default('') }}"
    file_f_option: ''
    file_action: "{{ item.file_action | default(omit) }}"
    template: "{{ item.template | default('') }}"
    template_f_option: ''
    template_action: "{{ item.template_action | default(omit) }}"
    params: "{{ item.params | default('') }}"
    process_local: ''

- name: "Fail if template but no params is specified"
  fail:
    msg: "Template specified, but no params file supplied"
  when:
  - template|trim != ''
  - params|trim == ''

- name: "Check if params file exists (if applicable)"
  stat:
    path: "{{ tmp_inv_dir }}{{ params }}"
  ignore_errors: yes
  register: params_result
  when:
  - params|trim != ''

- name: "Fail if params file doesn't exist (if applicable)"
  fail:
    msg: "{{ params }} - params file doesn't exist."
  when:
  - params|trim != ''
  - params_result.stat.exists == False

- name: "Determine location for the 'file' (if applicable)"
  vars:
    path: "{{ file }}"
  import_tasks: check-file-location.yml
  when:
  - file|trim != ''

- name: "Set 'file' values (if applicable)"
  set_fact:
    file: "{{ file_path }}"
    file_f_option: "{{ option_f }}" 
  when:
  - file|trim != ''

- name: "Determine location for the 'template' (if applicable)"
  vars:
    path: "{{ template }}"
  import_tasks: check-file-location.yml
  when:
  - template|trim != ''

- name: "Set 'template' values (if applicable)"
  set_fact:
    template: "{{ file_path }}"
    template_f_option: "{{ option_f }}" 
  when:
  - template|trim != ''

- name: "Set the target namespace option if supplied"
  set_fact:
    target_namespace: "-n {{ item.namespace }}"
  when:
  - item.namespace is defined
  - item.namespace|trim != ''

- name: "Create OpenShift objects based on static files for '{{ entry.object }}'"
  command: >
    oc {{ file_action }} {{ target_namespace }} -f {{ file }}
  register: command_result
  failed_when:
  - command_result.rc != 0
  - "'AlreadyExists' not in command_result.stderr"
  when:
  - file|trim != ''

- name: "Create OpenShift objects based on templates with params for '{{ entry.object }}'"
  shell: >
    oc process \
      {{ process_local }} \
      {{ template_f_option }} {{ template }} \
      {{ target_namespace }} \
      --param-file={{ tmp_inv_dir }}{{ item.params }} | \
    oc {{ template_action }} {{ target_namespace }} -f -
  register: command_result
  failed_when:
  - command_result.rc != 0
  - "'AlreadyExists' not in command_result.stderr"
  when:
  - template|trim != ''
  - params|trim != ''
